import matplotlib.pyplot as plt

def plot_bands(Kx, Ky, M):
    '''
    Plots an 4 x Nky x Nkx matrix M as a colorplot vs Kx and Ky for each value of
    the first index.

    This will plot over the 4 bands generated by a 4x4 Hamiltonian.
    '''
    fig, ax = plt.subplots(1, 4, figsize=(10, 2.5))

    for n in range(4):
        ax[n].pcolormesh(Kx, Ky, M[n], cmap='coolwarm')

    for a in ax.flatten():
        a.set_xticks([])
        a.set_yticks([])

    return fig, ax
